[package]
name = "server"
version = "0.1.0"
authors = ["rufus-stone <60827786+rufus-stone@users.noreply.github.com>"]
edition = "2018"


[dependencies]
simple_logger = "1.11.0"
log = "0.4.14"
structopt = "0.3.21"
consoles = { path = "../../libs/consoles" }
